// <auto-generated />
using System;
using Ithembahealth.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ithembahealth.Persistence.Migrations
{
    [DbContext(typeof(IthembahealthDbContext))]
    [Migration("20250730213752_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("BeneficiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmedByClinic")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = new Guid("3d33bf6d-25f6-4a8e-bca8-63b1637a6815"),
                            AppointmentDate = new DateTime(2025, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            BeneficiaryId = new Guid("0d7e0d46-898f-4801-9981-39dbda5484a4"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6663),
                            IsConfirmedByClinic = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("baa3b942-6e92-4771-9564-093cd6f323f9"),
                            ProviderId = new Guid("20d1d2a7-e5ac-46ce-8eee-a2512003a03f"),
                            Reason = "Consultation 0",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("025d39f3-3363-4d47-9f26-3a27c83952c6"),
                            AppointmentDate = new DateTime(2025, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            BeneficiaryId = new Guid("ff059982-f440-430b-94c9-a4a5cca80b36"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6670),
                            IsConfirmedByClinic = false,
                            LastModifiedBy = "",
                            PatientId = new Guid("9178e05e-7b8f-4f8e-bf4f-177a4774c006"),
                            ProviderId = new Guid("ce34ef0f-88ff-4d46-9e7e-6e75b5c914ef"),
                            Reason = "Consultation 1",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("bf2f7f1e-2236-430f-8cfa-4996435033a0"),
                            AppointmentDate = new DateTime(2025, 8, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            BeneficiaryId = new Guid("fdcd4437-8f57-4017-9107-f495ef5258db"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6675),
                            IsConfirmedByClinic = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("257bd265-04ad-4961-8cd9-d97468547b02"),
                            ProviderId = new Guid("12eef029-394b-40bf-b2be-4916a716e8f3"),
                            Reason = "Consultation 2",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("1b5749f7-7bdd-428d-a162-8beb9e63a2c4"),
                            AppointmentDate = new DateTime(2025, 8, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            BeneficiaryId = new Guid("24e4138e-aaf0-4e20-8f2e-85aaa1956fb7"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6681),
                            IsConfirmedByClinic = false,
                            LastModifiedBy = "",
                            PatientId = new Guid("b584ee0b-19ff-4c8e-94ae-d4618ad51ecc"),
                            ProviderId = new Guid("ad621338-6267-4424-87e1-be2df82a8605"),
                            Reason = "Consultation 3",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("410abe40-fee3-49be-909d-935a9e6f9823"),
                            AppointmentDate = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            BeneficiaryId = new Guid("2e34a24c-7685-4b91-bb74-ee77691fbc5a"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6686),
                            IsConfirmedByClinic = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("8cebead4-1404-4de2-a868-256753925914"),
                            ProviderId = new Guid("be7662a4-4192-4a1b-85b9-b1486d9103b9"),
                            Reason = "Consultation 4",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("74e0797a-5d9a-41c7-a653-4956224311eb"),
                            AppointmentDate = new DateTime(2025, 8, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6691),
                            IsConfirmedByClinic = false,
                            LastModifiedBy = "",
                            PatientId = new Guid("f3d06740-d23b-40e2-ac4f-e6f9b8b48435"),
                            ProviderId = new Guid("384edd91-22f0-4e1e-b028-c54657c6f733"),
                            Reason = "Consultation 5",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("d8f13061-4758-4f8c-b661-5d1673739865"),
                            AppointmentDate = new DateTime(2025, 8, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6695),
                            IsConfirmedByClinic = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("939df4ad-9e5d-474b-9c8d-b8627b323acc"),
                            ProviderId = new Guid("0088fb8d-d364-4e51-90c7-2a1938cb6361"),
                            Reason = "Consultation 6",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("e9190489-2240-4b80-a320-741681620411"),
                            AppointmentDate = new DateTime(2025, 8, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6700),
                            IsConfirmedByClinic = false,
                            LastModifiedBy = "",
                            PatientId = new Guid("7e026d24-9b96-4121-9d0a-07a62c1c4521"),
                            ProviderId = new Guid("51933af5-da80-44aa-b30c-c39685f2f11c"),
                            Reason = "Consultation 7",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("87255d56-f1e6-4d3e-873f-504e38d0529f"),
                            AppointmentDate = new DateTime(2025, 8, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6705),
                            IsConfirmedByClinic = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("45485474-6a89-4e04-b292-573d2eb9d481"),
                            ProviderId = new Guid("271ad1ee-ae06-4f3d-bae6-0819fa403b12"),
                            Reason = "Consultation 8",
                            Status = "Booked"
                        },
                        new
                        {
                            AppointmentId = new Guid("aae89a05-e860-4fe3-b3cc-6e48fa7b1d2d"),
                            AppointmentDate = new DateTime(2025, 8, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6710),
                            IsConfirmedByClinic = false,
                            LastModifiedBy = "",
                            PatientId = new Guid("90b0661b-487b-40ed-88ab-44bf51f3b469"),
                            ProviderId = new Guid("90a8b99b-dfb4-4433-9b85-2c21c5c8aeeb"),
                            Reason = "Consultation 9",
                            Status = "Booked"
                        });
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.AppointmentNote", b =>
                {
                    b.Property<Guid>("AppointmentNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentNoteId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentNotes");

                    b.HasData(
                        new
                        {
                            AppointmentNoteId = new Guid("b8f8144c-59ad-4e88-8d12-fc144563a9b0"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("3d33bf6d-25f6-4a8e-bca8-63b1637a6815"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6739),
                            LastModifiedBy = "",
                            Note = "Follow-up required"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("a0522caa-c236-45ea-89b3-dd1fe9f814af"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("025d39f3-3363-4d47-9f26-3a27c83952c6"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6742),
                            LastModifiedBy = "",
                            Note = "Lab results discussed"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("64439e76-0e72-4322-bf8f-3808e0517fe5"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("bf2f7f1e-2236-430f-8cfa-4996435033a0"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6743),
                            LastModifiedBy = "",
                            Note = "Prescription given"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("dc096833-e482-46fa-8e21-75bf2e781297"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("1b5749f7-7bdd-428d-a162-8beb9e63a2c4"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6745),
                            LastModifiedBy = "",
                            Note = "Routine check-in"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("e095e3cb-a52c-4f73-81e9-d3e63b3a3baa"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("410abe40-fee3-49be-909d-935a9e6f9823"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6747),
                            LastModifiedBy = "",
                            Note = "Follow-up required"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("b07a896c-c8cb-4a5d-aee0-58a8c5165c97"),
                            AddedBy = "Doctor",
                            AppointmentId = new Guid("74e0797a-5d9a-41c7-a653-4956224311eb"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6749),
                            LastModifiedBy = "",
                            Note = "Routine check-in"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("5b693767-65a6-498f-bf25-bd3b3907809a"),
                            AddedBy = "Doctor",
                            AppointmentId = new Guid("d8f13061-4758-4f8c-b661-5d1673739865"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6751),
                            LastModifiedBy = "",
                            Note = "Follow-up required"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("0f939e8a-c40c-4b2f-902d-7e48ff635fcf"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("e9190489-2240-4b80-a320-741681620411"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6752),
                            LastModifiedBy = "",
                            Note = "Routine check-in"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("8141ef21-4d7e-4604-841b-31dfd509e1c9"),
                            AddedBy = "Doctor",
                            AppointmentId = new Guid("87255d56-f1e6-4d3e-873f-504e38d0529f"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6754),
                            LastModifiedBy = "",
                            Note = "Lab results discussed"
                        },
                        new
                        {
                            AppointmentNoteId = new Guid("3174f25a-5ecd-4da2-b98c-e94150135cfb"),
                            AddedBy = "Nurse",
                            AppointmentId = new Guid("aae89a05-e860-4fe3-b3cc-6e48fa7b1d2d"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6756),
                            LastModifiedBy = "",
                            Note = "Lab results discussed"
                        });
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.AppointmentOTP", b =>
                {
                    b.Property<Guid>("AppointmentOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentOtpId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentOTPs");

                    b.HasData(
                        new
                        {
                            AppointmentOtpId = new Guid("a02a5766-0654-470c-8b78-cd97ddd2e305"),
                            AppointmentId = new Guid("3d33bf6d-25f6-4a8e-bca8-63b1637a6815"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6790),
                            IsUsed = false,
                            LastModifiedBy = "",
                            OTPCode = "562807",
                            SentAt = new DateTime(2025, 7, 30, 20, 53, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("ccce56c1-d63f-4b76-94ec-e5c53a258283"),
                            AppointmentId = new Guid("025d39f3-3363-4d47-9f26-3a27c83952c6"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6802),
                            IsUsed = true,
                            LastModifiedBy = "",
                            OTPCode = "842529",
                            SentAt = new DateTime(2025, 7, 30, 21, 5, 5, 933, DateTimeKind.Utc).AddTicks(2580),
                            UsedAt = new DateTime(2025, 7, 30, 21, 10, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("2273dcc0-1eb4-4f9e-bb64-85cf0b800457"),
                            AppointmentId = new Guid("bf2f7f1e-2236-430f-8cfa-4996435033a0"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6809),
                            IsUsed = true,
                            LastModifiedBy = "",
                            OTPCode = "216480",
                            SentAt = new DateTime(2025, 7, 30, 20, 25, 5, 933, DateTimeKind.Utc).AddTicks(2580),
                            UsedAt = new DateTime(2025, 7, 30, 20, 30, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("4f82a6eb-377d-49dc-bfe9-d33d80c8181a"),
                            AppointmentId = new Guid("1b5749f7-7bdd-428d-a162-8beb9e63a2c4"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6816),
                            IsUsed = true,
                            LastModifiedBy = "",
                            OTPCode = "865683",
                            SentAt = new DateTime(2025, 7, 30, 20, 32, 5, 933, DateTimeKind.Utc).AddTicks(2580),
                            UsedAt = new DateTime(2025, 7, 30, 20, 37, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("bdc769cc-5c9c-4b13-bfc6-04e85d52fe40"),
                            AppointmentId = new Guid("410abe40-fee3-49be-909d-935a9e6f9823"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6824),
                            IsUsed = true,
                            LastModifiedBy = "",
                            OTPCode = "193282",
                            SentAt = new DateTime(2025, 7, 30, 20, 39, 5, 933, DateTimeKind.Utc).AddTicks(2580),
                            UsedAt = new DateTime(2025, 7, 30, 20, 44, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("a937731e-508d-478c-beeb-90634055d4c8"),
                            AppointmentId = new Guid("74e0797a-5d9a-41c7-a653-4956224311eb"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6829),
                            IsUsed = false,
                            LastModifiedBy = "",
                            OTPCode = "413690",
                            SentAt = new DateTime(2025, 7, 30, 20, 56, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("8ed8574e-0dd8-4798-89ca-b134ae522c80"),
                            AppointmentId = new Guid("d8f13061-4758-4f8c-b661-5d1673739865"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6836),
                            IsUsed = true,
                            LastModifiedBy = "",
                            OTPCode = "226679",
                            SentAt = new DateTime(2025, 7, 30, 20, 45, 5, 933, DateTimeKind.Utc).AddTicks(2580),
                            UsedAt = new DateTime(2025, 7, 30, 20, 50, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("88027a1c-8bd6-4335-863d-d3b784e42f1e"),
                            AppointmentId = new Guid("e9190489-2240-4b80-a320-741681620411"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6843),
                            IsUsed = true,
                            LastModifiedBy = "",
                            OTPCode = "435332",
                            SentAt = new DateTime(2025, 7, 30, 21, 2, 5, 933, DateTimeKind.Utc).AddTicks(2580),
                            UsedAt = new DateTime(2025, 7, 30, 21, 7, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("86a1edd7-bf45-400f-848e-004ccce1c900"),
                            AppointmentId = new Guid("87255d56-f1e6-4d3e-873f-504e38d0529f"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6847),
                            IsUsed = false,
                            LastModifiedBy = "",
                            OTPCode = "651997",
                            SentAt = new DateTime(2025, 7, 30, 20, 59, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        },
                        new
                        {
                            AppointmentOtpId = new Guid("2a8fbfb1-0ff3-41f5-905f-ea7442ab505e"),
                            AppointmentId = new Guid("aae89a05-e860-4fe3-b3cc-6e48fa7b1d2d"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6852),
                            IsUsed = false,
                            LastModifiedBy = "",
                            OTPCode = "766681",
                            SentAt = new DateTime(2025, 7, 30, 20, 51, 5, 933, DateTimeKind.Utc).AddTicks(2580)
                        });
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.AppointmentStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CancelledAppointments")
                        .HasColumnType("int");

                    b.Property<int>("CompletedAppointments")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmedAppointments")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoShows")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAppointments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppointmentsStatistics");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.ClaimsAndPatient.ProviderClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HealthSavingsAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LinkedTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelationshipToPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthSavingsAccountId");

                    b.HasIndex("LinkedTransactionId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderClaims");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.HealthSavings.HealthSavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoDebitEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitSourceMpesaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalClaimed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalContributed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("HealthSavingsAccounts");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.HealthSavings.SavingsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HealthSavingsAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MpesaTransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthSavingsAccountId");

                    b.ToTable("SavingsTransaction");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Beneficiary", b =>
                {
                    b.Property<Guid>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("PatientId");

                    b.ToTable("Beneficiaries");

                    b.HasData(
                        new
                        {
                            BeneficiaryId = new Guid("0d7e0d46-898f-4801-9981-39dbda5484a4"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6546),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 1-1",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("baa3b942-6e92-4771-9564-093cd6f323f9"),
                            PhoneNumber = "27000000000",
                            Relationship = "Child"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("82540953-5545-4b2e-af2e-f7814b51b2cd"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6550),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 1-2",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("baa3b942-6e92-4771-9564-093cd6f323f9"),
                            PhoneNumber = "27000000001",
                            Relationship = "Parent"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("ff059982-f440-430b-94c9-a4a5cca80b36"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6554),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 2-1",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("9178e05e-7b8f-4f8e-bf4f-177a4774c006"),
                            PhoneNumber = "27000000010",
                            Relationship = "Spouse"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("40f06923-25a4-4dec-858d-10c2071ea03a"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6556),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 2-2",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("9178e05e-7b8f-4f8e-bf4f-177a4774c006"),
                            PhoneNumber = "27000000011",
                            Relationship = "Child"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("fdcd4437-8f57-4017-9107-f495ef5258db"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6558),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 3-1",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("257bd265-04ad-4961-8cd9-d97468547b02"),
                            PhoneNumber = "27000000020",
                            Relationship = "Child"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("4e82ba5f-5441-4fac-8f94-b9fe82b7930f"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6566),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 3-2",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("257bd265-04ad-4961-8cd9-d97468547b02"),
                            PhoneNumber = "27000000021",
                            Relationship = "Parent"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("24e4138e-aaf0-4e20-8f2e-85aaa1956fb7"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6568),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 4-1",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("b584ee0b-19ff-4c8e-94ae-d4618ad51ecc"),
                            PhoneNumber = "27000000030",
                            Relationship = "Child"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("4f7e03b0-e30a-449c-990b-90c18195a1d5"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6570),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 4-2",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("b584ee0b-19ff-4c8e-94ae-d4618ad51ecc"),
                            PhoneNumber = "27000000031",
                            Relationship = "Child"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("2e34a24c-7685-4b91-bb74-ee77691fbc5a"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6572),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 5-1",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("8cebead4-1404-4de2-a868-256753925914"),
                            PhoneNumber = "27000000040",
                            Relationship = "Parent"
                        },
                        new
                        {
                            BeneficiaryId = new Guid("27ed5233-3aed-4e88-a674-2410cbe155b1"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 7, 30, 21, 37, 51, 874, DateTimeKind.Utc).AddTicks(6574),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Beneficiary 5-2",
                            Gender = "",
                            IsActive = true,
                            LastModifiedBy = "",
                            PatientId = new Guid("8cebead4-1404-4de2-a868-256753925914"),
                            PhoneNumber = "27000000041",
                            Relationship = "Child"
                        });
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MpesaPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = new Guid("baa3b942-6e92-4771-9564-093cd6f323f9"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient0@example.com",
                            FirstName = "Patient0",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test0",
                            MpesaPhoneNumber = "+2666000000",
                            NationalId = "1000000000",
                            PhoneNumber = "+2666000000"
                        },
                        new
                        {
                            PatientId = new Guid("9178e05e-7b8f-4f8e-bf4f-177a4774c006"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient1@example.com",
                            FirstName = "Patient1",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test1",
                            MpesaPhoneNumber = "+2666000001",
                            NationalId = "1000000001",
                            PhoneNumber = "+2666000001"
                        },
                        new
                        {
                            PatientId = new Guid("257bd265-04ad-4961-8cd9-d97468547b02"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient2@example.com",
                            FirstName = "Patient2",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test2",
                            MpesaPhoneNumber = "+2666000002",
                            NationalId = "1000000002",
                            PhoneNumber = "+2666000002"
                        },
                        new
                        {
                            PatientId = new Guid("b584ee0b-19ff-4c8e-94ae-d4618ad51ecc"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient3@example.com",
                            FirstName = "Patient3",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test3",
                            MpesaPhoneNumber = "+2666000003",
                            NationalId = "1000000003",
                            PhoneNumber = "+2666000003"
                        },
                        new
                        {
                            PatientId = new Guid("8cebead4-1404-4de2-a868-256753925914"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient4@example.com",
                            FirstName = "Patient4",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test4",
                            MpesaPhoneNumber = "+2666000004",
                            NationalId = "1000000004",
                            PhoneNumber = "+2666000004"
                        },
                        new
                        {
                            PatientId = new Guid("f3d06740-d23b-40e2-ac4f-e6f9b8b48435"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient5@example.com",
                            FirstName = "Patient5",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test5",
                            MpesaPhoneNumber = "+2666000005",
                            NationalId = "1000000005",
                            PhoneNumber = "+2666000005"
                        },
                        new
                        {
                            PatientId = new Guid("939df4ad-9e5d-474b-9c8d-b8627b323acc"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient6@example.com",
                            FirstName = "Patient6",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test6",
                            MpesaPhoneNumber = "+2666000006",
                            NationalId = "1000000006",
                            PhoneNumber = "+2666000006"
                        },
                        new
                        {
                            PatientId = new Guid("7e026d24-9b96-4121-9d0a-07a62c1c4521"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient7@example.com",
                            FirstName = "Patient7",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test7",
                            MpesaPhoneNumber = "+2666000007",
                            NationalId = "1000000007",
                            PhoneNumber = "+2666000007"
                        },
                        new
                        {
                            PatientId = new Guid("45485474-6a89-4e04-b292-573d2eb9d481"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient8@example.com",
                            FirstName = "Patient8",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test8",
                            MpesaPhoneNumber = "+2666000008",
                            NationalId = "1000000008",
                            PhoneNumber = "+2666000008"
                        },
                        new
                        {
                            PatientId = new Guid("90b0661b-487b-40ed-88ab-44bf51f3b469"),
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient9@example.com",
                            FirstName = "Patient9",
                            IsPhoneNumberVerified = true,
                            LastModifiedBy = "",
                            LastName = "Test9",
                            MpesaPhoneNumber = "+2666000009",
                            NationalId = "1000000009",
                            PhoneNumber = "+2666000009"
                        });
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Provider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MpesaMerchantCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderId");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            ProviderId = new Guid("20d1d2a7-e5ac-46ce-8eee-a2512003a03f"),
                            ClinicName = "Clinic 0",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider0",
                            Email = "provider0@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 0",
                            MpesaMerchantCode = "MPESA000",
                            PhoneNumber = "+2666111000",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("ce34ef0f-88ff-4d46-9e7e-6e75b5c914ef"),
                            ClinicName = "Clinic 1",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider1",
                            Email = "provider1@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 1",
                            MpesaMerchantCode = "MPESA001",
                            PhoneNumber = "+2666111001",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("12eef029-394b-40bf-b2be-4916a716e8f3"),
                            ClinicName = "Clinic 2",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider2",
                            Email = "provider2@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 2",
                            MpesaMerchantCode = "MPESA002",
                            PhoneNumber = "+2666111002",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("ad621338-6267-4424-87e1-be2df82a8605"),
                            ClinicName = "Clinic 3",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider3",
                            Email = "provider3@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 3",
                            MpesaMerchantCode = "MPESA003",
                            PhoneNumber = "+2666111003",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("be7662a4-4192-4a1b-85b9-b1486d9103b9"),
                            ClinicName = "Clinic 4",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider4",
                            Email = "provider4@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 4",
                            MpesaMerchantCode = "MPESA004",
                            PhoneNumber = "+2666111004",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("384edd91-22f0-4e1e-b028-c54657c6f733"),
                            ClinicName = "Clinic 5",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider5",
                            Email = "provider5@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 5",
                            MpesaMerchantCode = "MPESA005",
                            PhoneNumber = "+2666111005",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("0088fb8d-d364-4e51-90c7-2a1938cb6361"),
                            ClinicName = "Clinic 6",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider6",
                            Email = "provider6@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 6",
                            MpesaMerchantCode = "MPESA006",
                            PhoneNumber = "+2666111006",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("51933af5-da80-44aa-b30c-c39685f2f11c"),
                            ClinicName = "Clinic 7",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider7",
                            Email = "provider7@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 7",
                            MpesaMerchantCode = "MPESA007",
                            PhoneNumber = "+2666111007",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("271ad1ee-ae06-4f3d-bae6-0819fa403b12"),
                            ClinicName = "Clinic 8",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider8",
                            Email = "provider8@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 8",
                            MpesaMerchantCode = "MPESA008",
                            PhoneNumber = "+2666111008",
                            Specialty = "General Medicine"
                        },
                        new
                        {
                            ProviderId = new Guid("90a8b99b-dfb4-4433-9b85-2c21c5c8aeeb"),
                            ClinicName = "Clinic 9",
                            CreatedBy = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Provider9",
                            Email = "provider9@clinic.com",
                            IsActive = true,
                            IsVerified = true,
                            LastModifiedBy = "",
                            Location = "District 9",
                            MpesaMerchantCode = "MPESA009",
                            PhoneNumber = "+2666111009",
                            Specialty = "General Medicine"
                        });
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Specialization", b =>
                {
                    b.Property<Guid>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecializationId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Specialization");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.WorkingHours", b =>
                {
                    b.Property<Guid>("WorkingHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("WorkingHoursId");

                    b.HasIndex("ProviderId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.Appointment", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId");

                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.AppointmentNote", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.Appointments.Appointment", "Appointment")
                        .WithMany("Notes")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.AppointmentOTP", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.Appointments.Appointment", "Appointment")
                        .WithMany("OTPs")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.ClaimsAndPatient.ProviderClaim", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.HealthSavings.HealthSavingsAccount", "HealthSavingsAccount")
                        .WithMany("ProviderClaims")
                        .HasForeignKey("HealthSavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ithembahealth.Domain.Entities.HealthSavings.SavingsTransaction", "LinkedTransaction")
                        .WithMany()
                        .HasForeignKey("LinkedTransactionId");

                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthSavingsAccount");

                    b.Navigation("LinkedTransaction");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.HealthSavings.HealthSavingsAccount", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Patient", "Patient")
                        .WithOne("HealthSavingsAccount")
                        .HasForeignKey("Ithembahealth.Domain.Entities.HealthSavings.HealthSavingsAccount", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.HealthSavings.SavingsTransaction", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.HealthSavings.HealthSavingsAccount", "HealthSavingsAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("HealthSavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthSavingsAccount");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Beneficiary", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Patient", "Patient")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Specialization", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Provider", "Provider")
                        .WithMany("Specializations")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.WorkingHours", b =>
                {
                    b.HasOne("Ithembahealth.Domain.Entities.PatientAndProvider.Provider", "Provider")
                        .WithMany("WorkingHours")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.Appointments.Appointment", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("OTPs");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.HealthSavings.HealthSavingsAccount", b =>
                {
                    b.Navigation("ProviderClaims");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Beneficiaries");

                    b.Navigation("HealthSavingsAccount");
                });

            modelBuilder.Entity("Ithembahealth.Domain.Entities.PatientAndProvider.Provider", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Specializations");

                    b.Navigation("WorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
